import React from "react";
import IMG1 from "../../assets/ngoconenct.png";
import IMG4 from "../../assets/Todolist.png";
import IMG3 from "../../assets/simon.png";
import IMG2 from "../../assets/fake.png";
import IMG5 from "../../assets/news.png";
import IMG6 from "../../assets/math.png";

import "./portfolio.css";

const Portfolio = () => {
  const soloProjects = [
    {
      id: 1,
      title: "NGOConnect",
      img: IMG1,
      description:
        "This dynamic platform serves as a centralized hub for NGOs, providing an avenue for volunteers and users to seamlessly apply for volunteer opportunities and contribute donations to specific NGOs.",
      technologies: "MERN Stack",
      link: "https://adventistlearningcenter-257375ab1970.herokuapp.com/",
      github: "https://github.com/ShivaniNikam1/final_NGO",
    },
    {
      id: 2,
      title: "To-Do-List",
      img: IMG4,
      description: "It is web-based to-do list application that leverages EJS for dynamic content rendering and MongoDB for data storage. Users can create, manage, and organize their tasks efficiently.",
      technologies: "HTML | CSS | EJS | Mongodb",
      link: "",
      github: "https://github.com/ShivaniNikam1/To-Do-List",
    },
    {
      id: 3,
      title: "VitalFlow",
      img: IMG2,
      description:
        "This innovative project enables users to seamlessly access information about nearby blood banks and actively participate in the noble cause of blood donation. ",
      technologies: "HTML | CSS | JS",
      link: "",
      github: "https://github.com/NidhiNayak08/VitalFlow",
    },
    {
      id: 4,
      title: "Simon Game",
      img: IMG3,
      description:
        "The Simon Game website is a digital adaptation of the classic memory game known as Simon. It offers an interactive and enjoyable experience for players of all ages. The core objective of the game is to mimic and remember a sequence of colors and sounds generated by the game, then reproduce that sequence in the correct order.",
      technologies: "JavaScript | CSS",
      link: "",
      github: "https://github.com/ShivaniNikam1/Simin_Game",
    },
    {
      id: 5,
      title: "World News",
      img: IMG5,
      description:
        "Fully responsive interactive website built based on Adobe XD design",
      technologies: "JavaScript | CSS",
      link: "https://meri-mg.github.io/Unilab-world-news/",
      github: "https://github.com/Meri-MG/Unilab-world-news",
    },
    {
      id: 6,
      title: "Math Resource",
      img: IMG6,
      description:
        "Real-world group project which is still in progress and will provide educational platform for future young developers",
      technologies: "JavaScript | Scss | Python",
      link: "https://lukinoo.github.io/math-resource/",
      github: "https://github.com/lukinoo/math-resource",
    },
  ];

  return (
    <section id="portfolio">
      <h5>My Recent Work</h5>
      <h2>Portfolio</h2>

      <div className="container portfolio__container">
        {soloProjects.map((pro) => (
          <article className="portfolio__item" key={pro.id}>
            <div className="portfolio__item-image">
              <img src={pro.img} alt={pro.title} />
            </div>
            <div className="portfolio__item-content">
              <h3>{pro.title}</h3>
              <p>{pro.description}</p>
              <p>{pro.technologies}</p>
            </div>
            <div className="portfolio__item-cta">
              <a
                href={pro.github}
                target="_blank"
                className="btn"
                rel="noreferrer"
              >
                GitHub
              </a>
              <a
                href={pro.link}
                target="_blank"
                className="btn btn-primary"
                rel="noreferrer"
              >
                Visit Website
              </a>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
};

export default Portfolio;
